import os
from pathlib import Path

from src.runtime_paths import DATA_DIR


SCALABLE_DB_FILE = Path(os.getenv("ATTENDANCE_DB_FILE", str(DATA_DIR / "scalable_attendance.db")))
VECTOR_INDEX_FILE = Path(os.getenv("ATTENDANCE_VECTOR_INDEX_FILE", str(DATA_DIR / "vector_index_v2.npz")))
EMBEDDING_SIZE = 256
FACE_SIZE = (112, 112)
MATCH_THRESHOLD = float(os.getenv("ATTENDANCE_MATCH_THRESHOLD", "0.68"))
AMBIGUITY_MARGIN = 0.04
ATTENDANCE_COOLDOWN_HOURS = 12
MAX_TOP_K = 5
MAX_FACES_PER_REQUEST = int(os.getenv("ATTENDANCE_MAX_FACES_PER_REQUEST", "10"))
RECOGNITION_CACHE_TTL_SECONDS = int(os.getenv("ATTENDANCE_RECOGNITION_CACHE_TTL_SECONDS", "5"))
DEFAULT_LIST_LIMIT = int(os.getenv("ATTENDANCE_DEFAULT_LIST_LIMIT", "100"))
EMBEDDING_BACKEND = os.getenv("ATTENDANCE_EMBEDDING_BACKEND", "lbph")
VECTOR_INDEX_BACKEND = os.getenv("ATTENDANCE_VECTOR_INDEX_BACKEND", "numpy")
BREATH_ANALYZER_MODE = os.getenv("ATTENDANCE_BREATH_ANALYZER_MODE", "mock").strip().lower()
BREATH_ALCOHOL_THRESHOLD_PPB = float(os.getenv("ATTENDANCE_BREATH_ALCOHOL_THRESHOLD_PPB", "35"))
BREATH_CANNABIS_THRESHOLD_PPB = float(os.getenv("ATTENDANCE_BREATH_CANNABIS_THRESHOLD_PPB", "25"))
BREATH_MOCK_ALCOHOL_PPB = float(os.getenv("ATTENDANCE_BREATH_MOCK_ALCOHOL_PPB", "0"))
BREATH_MOCK_CANNABIS_PPB = float(os.getenv("ATTENDANCE_BREATH_MOCK_CANNABIS_PPB", "0"))
BREATH_SAMPLE_SECONDS = max(0.0, float(os.getenv("ATTENDANCE_BREATH_SAMPLE_SECONDS", "10")))
BREATH_SAMPLE_INTERVAL_SECONDS = max(0.0, float(os.getenv("ATTENDANCE_BREATH_SAMPLE_INTERVAL_SECONDS", "0.05")))
BREATH_SPI_DEVICE = os.getenv("ATTENDANCE_BREATH_SPI_DEVICE", "/dev/spidev1.0").strip() or "/dev/spidev1.0"
BREATH_SPI_MODE = int(os.getenv("ATTENDANCE_BREATH_SPI_MODE", "0"))
BREATH_SPI_SPEED_HZ = int(os.getenv("ATTENDANCE_BREATH_SPI_SPEED_HZ", "1000000"))
BREATH_BOARD_ENABLE_GPIO = int(os.getenv("ATTENDANCE_BREATH_BOARD_ENABLE_GPIO", "257"))
BREATH_POWER_SETTLE_SECONDS = max(0.0, float(os.getenv("ATTENDANCE_BREATH_POWER_SETTLE_SECONDS", "0.01")))
BREATH_PID_SETTLE_SECONDS = max(0.0, float(os.getenv("ATTENDANCE_BREATH_PID_SETTLE_SECONDS", "0.01")))
BREATH_ADC_SETTLE_SECONDS = max(0.0, float(os.getenv("ATTENDANCE_BREATH_ADC_SETTLE_SECONDS", "0.01")))
BREATH_SAMPLE_AGGREGATION = os.getenv("ATTENDANCE_BREATH_SAMPLE_AGGREGATION", "mean").strip().lower() or "mean"
BREATH_ADC_BITS = max(1, int(os.getenv("ATTENDANCE_BREATH_ADC_BITS", "16")))
BREATH_ADC_VREF = float(os.getenv("ATTENDANCE_BREATH_ADC_VREF", "2.5"))
BREATH_ADC_GAIN = float(os.getenv("ATTENDANCE_BREATH_ADC_GAIN", "2.0"))
BREATH_ADC_BASELINE = float(os.getenv("ATTENDANCE_BREATH_ADC_BASELINE", "0"))
BREATH_ALCOHOL_SOURCE = os.getenv("ATTENDANCE_BREATH_ALCOHOL_SOURCE", "mock").strip().lower() or "mock"
BREATH_ADC_TO_ALCOHOL_SCALE = float(os.getenv("ATTENDANCE_BREATH_ADC_TO_ALCOHOL_SCALE", "1"))
BREATH_ADC_TO_ALCOHOL_OFFSET = float(os.getenv("ATTENDANCE_BREATH_ADC_TO_ALCOHOL_OFFSET", "0"))
BREATH_PLACEHOLDER_ALCOHOL_MIN_PPB = float(os.getenv("ATTENDANCE_BREATH_PLACEHOLDER_ALCOHOL_MIN_PPB", "0"))
BREATH_PLACEHOLDER_ALCOHOL_MAX_PPB = float(os.getenv("ATTENDANCE_BREATH_PLACEHOLDER_ALCOHOL_MAX_PPB", "10"))
BREATH_ADC_TO_CANNABIS_SCALE = float(os.getenv("ATTENDANCE_BREATH_ADC_TO_CANNABIS_SCALE", "1"))
BREATH_ADC_TO_CANNABIS_OFFSET = float(os.getenv("ATTENDANCE_BREATH_ADC_TO_CANNABIS_OFFSET", "0"))
ALLOW_BACKEND_FALLBACK = os.getenv("ATTENDANCE_ALLOW_BACKEND_FALLBACK", "true").lower() in {"1", "true", "yes", "on"}
LBPH_CONFIDENCE_THRESHOLD = float(os.getenv("ATTENDANCE_LBPH_CONFIDENCE_THRESHOLD", "78"))
MATCH_CONFIRMATION_FRAMES = int(os.getenv("ATTENDANCE_MATCH_CONFIRMATION_FRAMES", "4"))
# Rolling gap allowance between consecutive confirmation frames. On embedded
# devices a single recognition round-trip can take >1s, so 2s made pending
# matches expire mid-confirmation and identification never completed.
MATCH_CONFIRMATION_WINDOW_SECONDS = int(os.getenv("ATTENDANCE_MATCH_CONFIRMATION_WINDOW_SECONDS", "6"))
# Fast accept still requires >=2 consecutive agreeing frames (see
# _confirm_match_candidate); this is the per-frame score bar for that path.
FAST_ACCEPT_SCORE = float(os.getenv("ATTENDANCE_FAST_ACCEPT_SCORE", "0.97"))
MATCH_CONFIRMATION_MIN_AVG_SCORE = float(os.getenv("ATTENDANCE_MATCH_CONFIRMATION_MIN_AVG_SCORE", "0.80"))
MATCH_CONFIRMATION_MIN_BEST_SCORE = float(os.getenv("ATTENDANCE_MATCH_CONFIRMATION_MIN_BEST_SCORE", "0.84"))
OPEN_SET_MIN_SCORE = float(os.getenv("ATTENDANCE_OPEN_SET_MIN_SCORE", "0.72"))
OPEN_SET_SUPPORT_SCORE = float(os.getenv("ATTENDANCE_OPEN_SET_SUPPORT_SCORE", "0.66"))
OPEN_SET_MIN_CENTROID_SCORE = min(0.70, float(os.getenv("ATTENDANCE_OPEN_SET_MIN_CENTROID_SCORE", "0.70")))
MAX_PROFILE_CENTROID_THRESHOLD = min(
    0.70,
    float(os.getenv("ATTENDANCE_MAX_PROFILE_CENTROID_THRESHOLD", "0.70")),
)
OPEN_SET_CENTROID_MARGIN = float(os.getenv("ATTENDANCE_OPEN_SET_CENTROID_MARGIN", "0.08"))
MIN_ENROLLMENT_IMAGES = int(os.getenv("ATTENDANCE_MIN_ENROLLMENT_IMAGES", "5"))
DESCRIPTOR_VARIANT_REQUIRED_HITS = int(os.getenv("ATTENDANCE_DESCRIPTOR_VARIANT_REQUIRED_HITS", "2"))
SINGLE_PROFILE_MIN_SCORE = float(os.getenv("ATTENDANCE_SINGLE_PROFILE_MIN_SCORE", "0.84"))
SINGLE_PROFILE_SUPPORT_SCORE = float(os.getenv("ATTENDANCE_SINGLE_PROFILE_SUPPORT_SCORE", "0.72"))
SINGLE_PROFILE_MIN_CENTROID_SCORE = min(
    0.70,
    float(os.getenv("ATTENDANCE_SINGLE_PROFILE_MIN_CENTROID_SCORE", "0.70")),
)
SINGLE_PROFILE_REQUIRED_SUPPORT_HITS = int(os.getenv("ATTENDANCE_SINGLE_PROFILE_REQUIRED_SUPPORT_HITS", "3"))
SINGLE_PROFILE_LBPH_CONFIDENCE_THRESHOLD = float(
    os.getenv("ATTENDANCE_SINGLE_PROFILE_LBPH_CONFIDENCE_THRESHOLD", "55")
)
SINGLE_PROFILE_CONFIRMATION_FRAMES = int(os.getenv("ATTENDANCE_SINGLE_PROFILE_CONFIRMATION_FRAMES", "5"))
SINGLE_PROFILE_CONFIRMATION_MIN_AVG_SCORE = float(
    os.getenv("ATTENDANCE_SINGLE_PROFILE_CONFIRMATION_MIN_AVG_SCORE", "0.86")
)
SINGLE_PROFILE_CONFIRMATION_MIN_BEST_SCORE = float(
    os.getenv("ATTENDANCE_SINGLE_PROFILE_CONFIRMATION_MIN_BEST_SCORE", "0.88")
)
SINGLE_PROFILE_CONFIRMATION_MIN_FLOOR_SCORE = float(
    os.getenv("ATTENDANCE_SINGLE_PROFILE_CONFIRMATION_MIN_FLOOR_SCORE", "0.82")
)
MIN_FACE_WIDTH = int(os.getenv("ATTENDANCE_MIN_FACE_WIDTH", "90"))
MIN_FACE_HEIGHT = int(os.getenv("ATTENDANCE_MIN_FACE_HEIGHT", "90"))
MIN_FACE_BLUR_VARIANCE = float(os.getenv("ATTENDANCE_MIN_FACE_BLUR_VARIANCE", "30"))
MIN_FACE_BRIGHTNESS = float(os.getenv("ATTENDANCE_MIN_FACE_BRIGHTNESS", "35"))
MAX_FACE_BRIGHTNESS = float(os.getenv("ATTENDANCE_MAX_FACE_BRIGHTNESS", "220"))
